--------------------------------------------------------------
-- AUDIT REPORT TABLE
--------------------------------------------------------------
PROMPT CREATE SEQUENCE bt_account_seq_01
CREATE SEQUENCE DBUA_AUDIT_REPORT_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  NOCYCLE
  NOORDER
  CACHE 20
/

CREATE TABLE DBUA_AUDIT_REPORT(
ID NUMBER(28) PRIMARY KEY,
SERVERNAME   VARCHAR2(50) NOT NULL,
DATABASE VARCHAR2(20) NOT NULL,
USERNAME  VARCHAR2(30) NOT NULL,
PRIVILEGS_AND_ROLES VARCHAR2(100),
LOGIN_TYPE VARCHAR2(400) NULL,
AUDIT_DATE DATE DEFAULT SYSDATE NULL
);

INSERT INTO DBUA_AUDIT_REPORT VALUES(DBUA_AUDIT_REPORT_SEQ.NEXTVAL, 'TEST_SERVER_NAME','TEST_DATABASE','TEST_USER','TEST_PREV', '', sysdate);
SELECT * FROM  DBUA_AUDIT_REPORT;



--------------------------------------------------------------
-- CONFIGURATINO TABLES
--------------------------------------------------------------


PROMPT CREATE SEQUENCE bt_account_seq_01
CREATE SEQUENCE DBUA_INVENTRY_SEQ
  MINVALUE 1
  MAXVALUE 100000
  INCREMENT BY 1
  NOCYCLE
  NOORDER
  CACHE 20
/

PROMPT CREATE SEQUENCE bt_account_seq_01
CREATE SEQUENCE DBUA_QUERY_SEQ
  MINVALUE 1
  MAXVALUE 1000
  INCREMENT BY 1
  NOCYCLE
  NOORDER
  CACHE 20
/


CREATE TABLE DBUA_DB_TYPE (
db_type_id NUMBER(2)  PRIMARY KEY,
database_type VARCHAR2(20) NOT NULL,
description VARCHAR2(100)
);

CREATE TABLE DBUA_QUERY (
query_id NUMBER(3)  PRIMARY KEY,
db_type_id NUMBER(2) NOT NULL,
query VARCHAR2(3000) NOT NULL,
FOREIGN KEY (db_type_id) REFERENCES DBUA_DB_TYPE(db_type_id)
);


CREATE TABLE DBUA_INVENTRY (
inventry_id NUMBER(5) PRIMARY KEY,
server VARCHAR2(20) NOT NULL,
db_type_id NUMBER(2) NOT NULL,
database_name VARCHAR2(30) NOT NULL,
port VARCHAR2(5),
sid  VARCHAR2(10),
userid VARCHAR2(10) NOT NULL,
pwd VARCHAR2(400) NOT NULL,
FOREIGN KEY (db_type_id) REFERENCES DBUA_DB_TYPE(db_type_id)
);

--DROP TABLE DBUA_INVENTRY;
--DROP TABLE DBUA_QUERY;
--DROP TABLE DBUA_DB_TYPE;

--TRUNCATE TABLE DBUA_QUERY;
--TRUNCATE TABLE DBUA_INVENTRY;



--------------------------------------------------------------
-- CONFIGURATION ENTRIES
--------------------------------------------------------------



INSERT INTO  DBUA_DB_TYPE VALUES(1,'oracle', 'oracle database server');
INSERT INTO  DBUA_DB_TYPE VALUES(2,'vertica', 'vertica database server');
INSERT INTO  DBUA_DB_TYPE VALUES(3,'mssql', 'mssql database server');

INSERT INTO  DBUA_QUERY VALUES(DBUA_QUERY_SEQ.NEXTVAL,1,'SELECT 
a.SERVER_NAME AS SERVERNAME, 
a.DATABASE_NAME AS DATABASE, 
b.GRANTEE AS USERNAME, 
b.PRIVILEGE AS PRIVILEGS_AND_ROLES,
''NA'' AS LOGIN_TYPE
FROM (
    SELECT 
      GRANTEE,
      PRIVILEGE    
    FROM
      DBA_SYS_PRIVS   
    WHERE GRANTEE IN (SELECT USERNAME FROM DBA_USERS)     
    UNION      
    SELECT
      GRANTEE,
      PRIVILEGE
    FROM
      DBA_SYS_PRIVS
    WHERE GRANTEE IN (SELECT USERNAME FROM DBA_USERS)
) b,
(SELECT HOST_NAME AS SERVER_NAME, INSTANCE_NAME AS DATABASE_NAME FROM V$INSTANCE) a

ORDER BY 1,2,3,4');

INSERT INTO  DBUA_QUERY VALUES(DBUA_QUERY_SEQ.NEXTVAL,2,'SELECT b.node_address AS HOSTNAME , 
a.database_name as DATABASE, 
grantee as USERNAME, 
privileges_description as PRIVILEGS_AND_ROLES,
''NA'' as LOGIN_TYPE
FROM 
  GRANTS , 
  (select database_name from databases) a,
  (select node_address from nodes limit 1 offset 0) b
  where grantee not in (''dbadmin'',''public'')');


INSERT INTO  DBUA_QUERY VALUES(DBUA_QUERY_SEQ.NEXTVAL,3,'SELECT servername as SERVERNAME, dbname as ''DATABASE'', username as USERNAME,
Permissions_user as PRIVILEGS_AND_ROLES, logintype as LOGIN_TYPE from dbuser');



INSERT INTO  DBUA_INVENTRY VALUES(DBUA_INVENTRY_SEQ.NEXTVAL, '192.168.72.171', 1,'KVLALI',
'1522',
'KVLALI',
'utility',
'3339333433353337333533373334333433333339364637323631363336433635'
);

INSERT INTO  DBUA_INVENTRY VALUES(DBUA_INVENTRY_SEQ.NEXTVAL, '192.168.72.173', 1,'d2he',
'1521',
'd2he',
'utility',
'3332333233323332333233353337333633313338364637323631363336433635'
);

INSERT INTO  DBUA_INVENTRY VALUES(DBUA_INVENTRY_SEQ.NEXTVAL, '192.168.72.163', 2,'mydb',
'5433',
'none',
'dbadmin',
'33313332333233323335333433383337333533343736363537323734363936333631'
);

INSERT INTO  DBUA_INVENTRY VALUES(DBUA_INVENTRY_SEQ.NEXTVAL, '192.168.72.55', 3,'master',
'1434',
'NULL',
'sa',
'333133323333333433353336333733383339333036453635373036313643333133323333'
);

-- SELECT * FROM  DBUA_DB_TYPE;
-- SELECT * FROM  DBUA_QUERY;
-- SELECT * FROM  DBUA_INVENTRY;


-- DROP TABLE dbua_audit_report;
-- DROP TABLE dbua_inventry;
-- DROP TABLE dbua_query;
-- DROP TABLE dbua_db_type;

-- DROP SEQUENCE dbua_audit_report_seq;
-- DROP SEQUENCE dbua_inventry_seq;
-- DROP SEQUENCE dbua_query_seq;
